#!/usr/bin/env python3
"""Build a safe Themis "starter" policy from categorized known-value lists.

Themis is a *literal* matcher, so it governs KNOWN VALUES - denied entities,
compromised accounts, watched customers, specific card numbers, internal project
names. This turns per-category value lists (`values/*.txt`) into a deployable
`.nol` policy that maps every value to a short governance token.

Field workflow: a starter policy already matches the demo corpus, so it produces
real redactions out of the box. For a real customer, drop their own values into
the lists and regenerate - no rule-authoring by hand.

Two guards make the output safe to hand to a customer, both from our own findings:
  - Tokens are <= 15 chars and distinct, so the runtime's 15-char truncation
    (ISSUE-005) never garbles or collapses them.
  - No value may contain another. Overlapping/containing literals make Themis
    silently corrupt output (ISSUE-004); the generator REFUSES rather than emit
    an unsafe policy. (A production policy should also run the framework's full
    overlapping-match detector; containment is the common trap for entity lists.)

Regenerate:  python demos/policies/build_policy.py
"""

from __future__ import annotations

from pathlib import Path

MAX_TOKEN_LENGTH = 15

# (list file, governance token, human label). Tokens kept <= 15 chars, distinct.
CATEGORIES: list[tuple[str, str, str]] = [
    ("bad_ips.txt", "[BLOCKED_IP]", "Malicious / blocked IP addresses"),
    ("compromised_accounts.txt", "[COMP_ACCT]", "Compromised account identifiers"),
    ("customers.txt", "[CUSTOMER]", "Watched customer names"),
    ("denied_entities.txt", "[DENIED]", "Denied / sanctioned entities"),
    ("internal_projects.txt", "[PROJECT]", "Internal project names"),
    ("payment_cards.txt", "[CARD]", "Payment card numbers"),
    ("regulated_datasets.txt", "[REGULATED]", "Regulated dataset references"),
]

HERE = Path(__file__).resolve().parent
VALUES_DIR = HERE / "values"
OUTPUT = HERE / "starter-known-values.nol"


def load_categories(values_dir: Path) -> list[tuple[str, str, list[str]]]:
    """Return [(token, label, values)] for each category with a values file."""

    loaded = []
    for filename, token, label in CATEGORIES:
        path = values_dir / filename
        if not path.is_file():
            continue
        values = [line.strip() for line in path.read_text().splitlines() if line.strip()]
        if values:
            loaded.append((token, label, values))
    return loaded


def check_safe(categories: list[tuple[str, str, list[str]]]) -> None:
    """Raise ValueError unless the policy is safe to deploy.

    Enforces token budget/distinctness (ISSUE-005) and refuses containing
    literals (ISSUE-004).
    """

    tokens = [token for token, _, _ in categories]
    for token in tokens:
        if len(token) > MAX_TOKEN_LENGTH:
            raise ValueError(
                f"Token {token!r} exceeds {MAX_TOKEN_LENGTH} chars; it would "
                "truncate at runtime (ISSUE-005)."
            )
    if len(set(tokens)) != len(tokens):
        raise ValueError("Governance tokens must be distinct.")

    all_values = [value for _, _, values in categories for value in values]
    if len(set(all_values)) != len(all_values):
        raise ValueError("Duplicate values across the lists; each must be unique.")

    # Containment: no value may be a substring of another, or Themis corrupts
    # the output where their matches overlap (ISSUE-004).
    for outer in all_values:
        for inner in all_values:
            if inner != outer and inner in outer:
                raise ValueError(
                    f"Value {inner!r} is contained in {outer!r}; overlapping "
                    "literals trigger ISSUE-004. Remove one or make them disjoint."
                )


def build_nol(categories: list[tuple[str, str, list[str]]]) -> str:
    """Render the .nol policy text, grouped by category with comments."""

    lines = [
        "# Themis starter policy - known governed values (literal matching).",
        "# Generated by demos/policies/build_policy.py; edit values/*.txt and regenerate.",
        "",
    ]
    for token, label, values in categories:
        lines.append(f"# {label} -> {token}")
        for value in values:
            escaped = value.replace('"', '\\"')
            lines.append(f'"{escaped}" -> "{token}";')
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    categories = load_categories(VALUES_DIR)
    check_safe(categories)
    OUTPUT.write_text(build_nol(categories))
    rule_count = sum(len(values) for _, _, values in categories)
    print(f"Wrote {OUTPUT.name}: {rule_count} rules across {len(categories)} categories.")


if __name__ == "__main__":
    main()
